/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVehicleAccess } from "./IVehicleAccess";
export type { VehicleAccess } from "./VehicleAccess";
