/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IUserContract__factory } from "./IUserContract__factory";
export { UserContract__factory } from "./UserContract__factory";
