/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./access";
export type { access };
import type * as agent from "./agent";
export type { agent };
import type * as base from "./base";
export type { base };
import type * as baseFactory from "./baseFactory";
export type { baseFactory };
import type * as insurance from "./insurance";
export type { insurance };
import type * as insurer from "./insurer";
export type { insurer };
import type * as nft from "./nft";
export type { nft };
import type * as user from "./user";
export type { user };
import type * as vehicleAccess from "./vehicleAccess";
export type { vehicleAccess };
import type * as vehicleFactory from "./vehicleFactory";
export type { vehicleFactory };
import type * as vehicleOwner from "./vehicleOwner";
export type { vehicleOwner };
export type { VehicleSystemContract } from "./VehicleSystemContract";
