/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseContract__factory } from "./BaseContract__factory";
export { BaseContractVehicleSystem__factory } from "./BaseContractVehicleSystem__factory";
