/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseContract } from "./BaseContract";
export type { BaseContractVehicleSystem } from "./BaseContractVehicleSystem";
