/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVehicleAccess__factory } from "./IVehicleAccess__factory";
export { VehicleAccess__factory } from "./VehicleAccess__factory";
