/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVehicleOwner__factory } from "./IVehicleOwner__factory";
export { VehicleOwner__factory } from "./VehicleOwner__factory";
