/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVehicleFactory } from "./IVehicleFactory";
export type { VehicleFactory } from "./VehicleFactory";
