/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVehicleFactory__factory } from "./IVehicleFactory__factory";
export { VehicleFactory__factory } from "./VehicleFactory__factory";
